id = "tokyo-midnight"
name = "Tokyo Midnight Themes"
version = "0.1.0"
schema_version = 1
authors = ["pranshuj73 <hello@pranshujha.com>"]
description = "Tokyo Midnight Themes"
repository = "https://github.com/pranshuj73/zed-tokyo-midnight"
